--- #YAML:1.0
name:                POE-Component-Log4perl
version:             0.03
abstract:            Perl extension for the POE Environemt
license:             ~
author:              
    - Kevin L. Esteb <kesteb@wsipc.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Log::Log4perl:                 0
    POE:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
